version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - wordpress
            - mysqldb
        networks:
            - default2
    mysqldb:
        image: mysql:8
        container_name: ${MYSQL_HOST}
        command:  '--default-authentication-plugin=mysql_native_password' 
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        networks:
            - default2
        volumes:
            - "./data/db/mysql:/var/lib/mysql"             
    wordpress:
        image: wordpress:latest
        restart: always
        volumes:
            - "./wordpress:/var/www/html/wp-content"
        environment:
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wp}
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-P@ssw0rd12345}
        depends_on:
            - mysqldb
        networks:
            - default2

networks:
    default2:
        driver: bridge
